### ISSUE TITLE
[JS Error] TypeError: def.getLimitNum is not a function

### ISSUE THREAD

**Issue by magic-space** [nroutasuo/level13#172]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

Stacktrace:
TypeError: def.getLimitNum is not a function%0A    at constructor.updateWorkerMaxDescriptions (https://level13.sytes.net/src/game/systems/ui/UIOutCampSystem.js:259:31)%0A    at constructor.refresh (https://level13.sytes.net/src/game/systems/ui/UIOutCampSystem.js:139:18)%0A    at constructor.onTabChanged (https://level13.sytes.net/src/game/systems/ui/UIOutCampSystem.js:577:22)%0A    at https://level13.sytes.net/src/game/GlobalSignals.js:69:30%0A    at r.execute (https://level13.sytes.net/lib/ash/ash.min.js:14:4611)%0A    at n.Signal.dispatch (https://level13.sytes.net/lib/ash/ash.min.js:14:6738)%0A    at constructor.onTabClicked (https://level13.sytes.net/src/game/UIFunctions.js:598:36)%0A    at constructor.showTab (https://level13.sytes.net/src/game/UIFunctions.js:964:10)%0A    at constructor.enterCamp (https://level13.sytes.net/src/game/PlayerActionFunctions.js:447:30)%0A    at constructor.performAction (https://level13.sytes.net/src/game/PlayerActionFunctions.js:235:41)

**Comment by magic-space** [comment]
I fix it by my self.

 Thank you for the nice script
