### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'entity' of null

### ISSUE THREAD

**Issue by dbrbs** [nroutasuo/level13#185]
Details:
I was just opening the game and waiting for it to load while doing things on another tab.

Seed: 8305
Position: 4.-12.34 (inCamp: false)
Stacktrace:
TypeError: Cannot read property 'entity' of null
    at constructor.updateItemStats (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:543:95)
    at constructor.onGameShown (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:808:9)
    at https://nroutasuo.github.io/level13/src/game/GlobalSignals.js:77:15
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.showGame (https://nroutasuo.github.io/level13/src/game/UIFunctions.js:590:35)
    at https://nroutasuo.github.io/level13/src/game/systems/GameManager.js:157:29

**Comment by nroutasuo** [comment]
Thanks for reporting, I'll fix this for the next update!
Did this happen only once or are you blocked by it?

**Comment by dbrbs** [comment]
Hello, the error went away when I refreshed the page and waited it for it to load while focused on that tab only.

**Comment by nroutasuo** [comment]
I've added a fix for this for the upcoming version.
