### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'entity' of null

### ISSUE THREAD

**Issue by Jimmy45642B** [nroutasuo/level13#200]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

Seed: 4244
Position: 13.0.0 (inCamp: true)
Stacktrace:
TypeError: Cannot read property 'entity' of null
    at constructor.updateItemStats (https://likexia.gitee.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:543:95)
    at constructor.onGameShown (https://likexia.gitee.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:808:9)
    at https://likexia.gitee.io/level13/src/game/GlobalSignals.js:77:15
    at r.execute (https://likexia.gitee.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://likexia.gitee.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.showGame (https://likexia.gitee.io/level13/src/game/UIFunctions.js:590:35)
    at https://likexia.gitee.io/level13/src/game/systems/GameManager.js:157:29

**Comment by SoMall-dumpling** [comment]
最好还是提一句bug弹窗弹出来前你都做了哪些操作吧。
You may mention what you did before the bug exists.

**Comment by nroutasuo** [comment]
Thanks for reporting! By the looks of the stack trace it actually happens right at the start of the game before the player has time to do much.

**Comment by nroutasuo** [comment]
Added a fix for the upcoming version.
