### ISSUE TITLE
[JS Error] TypeError: Cannot read properties of null (reading 'entity')

### ISSUE THREAD

**Issue by ACorridorWanderer** [nroutasuo/level13#221]
Details:
What happened is that I loaded in the game than got out of the tab. When I came back in, it didn't load! But, if I am on the tab, it successfully loads. An easy fix, but the bug isn't why I wanted to do this. I just really wanted to say that this is an amazing game and I really enjoy it. I personally think that you are doing a great job and you are doing great! I have made it to level 8 and I have a literal battle-axe. I hope that you will read this. Thank you for your time.
![Screenshot 2022-01-28 12 01 20 PM](https://user-images.githubusercontent.com/98608138/151589719-ed37d995-2433-4708-b894-8ae3196e8fa1.png)
]

Seed: 8158
Position: 9.-12.-1 (inCamp: true)
Stacktrace:
TypeError: Cannot read properties of null (reading 'entity')
    at constructor.updateItemStats (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:543:95)
    at constructor.onGameShown (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutHeaderSystem.js:808:9)
    at https://nroutasuo.github.io/level13/src/game/GlobalSignals.js:77:15
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.showGame (https://nroutasuo.github.io/level13/src/game/UIFunctions.js:590:35)
    at https://nroutasuo.github.io/level13/src/game/systems/GameManager.js:157:29

**Comment by nroutasuo** [comment]
Thank you for reporting the bug and for the kind feedback!

**Comment by nroutasuo** [comment]
This should be fixed in the upcoming version.
