### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'btnClearWorkshop' of undefined

### ISSUE THREAD

**Issue by jessefjxm** [nroutasuo/level13#44]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]
Happens when I trying to go SW at level 12 here:
![image](https://user-images.githubusercontent.com/1498592/38338126-2ae6b374-3836-11e8-85ef-af6f1b700d24.png)

Stacktrace:
TypeError: Cannot read property 'btnClearWorkshop' of undefined
    at constructor.updateLevelPageActions (file:///D:/WHY/Downloads/level13-master/src/game/systems/ui/UIOutLevelSystem.js:232:32)
    at constructor.updateLevelPage (file:///D:/WHY/Downloads/level13-master/src/game/systems/ui/UIOutLevelSystem.js:184:9)
    at constructor.update (file:///D:/WHY/Downloads/level13-master/src/game/systems/ui/UIOutLevelSystem.js:125:10)
    at constructor.update (file:///D:/WHY/Downloads/level13-master/lib/ash/ash.min.js:14:15165)
    at r.execute (file:///D:/WHY/Downloads/level13-master/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (file:///D:/WHY/Downloads/level13-master/lib/ash/ash.min.js:14:6738)
    at constructor.tick (file:///D:/WHY/Downloads/level13-master/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment]
Thanks for reporting, I'll have a look

**Comment by nroutasuo** [comment]
This has been fixed in current master.
