### ISSUE TITLE
[JS Error] ReferenceError: item is not defined

### ISSUE THREAD

**Issue by darkmir** [nroutasuo/level13#72]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

Stacktrace:
ReferenceError: item is not defined
    at constructor.refreshCurrent (http://likexia.gitee.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:61:107)
    at constructor.initializePopup (http://likexia.gitee.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:43:18)
    at constructor.update (http://likexia.gitee.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:36:22)
    at constructor.update (http://likexia.gitee.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (http://likexia.gitee.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (http://likexia.gitee.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (http://likexia.gitee.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by darkmir** [comment]
Aftering updating the tech,  I got a attendant. But when I check the attack, it doesn't add with the parameter that the attendant provided. And I have no idea how can I dismiss the current attendant or rehire another one.

**Comment by nroutasuo** [comment]
Fixed for the upcoming update. Thanks for reporting!
Please consider playing the official version of the game in the future.
