### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'toggleClass' of undefined

### ISSUE THREAD

**Issue by Unihedro** [nroutasuo/level13#73]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]
I was looking at the information for trading with trade partner Bone thingy which unlocked in floor11 and I touched the slider and I got the window that says I found a bug

Stacktrace:

```
TypeError: Cannot read property 'toggleClass' of undefined
    at constructor.updateButtonCalloutCosts (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:237:27)
    at constructor.updateButtonCallout (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:205:26)
    at constructor.updateButtons (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:157:9)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:134:18)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)
```

Bonus trace

![image](https://user-images.githubusercontent.com/5595067/44301391-5d1db180-a348-11e8-93a0-c190f6da89fd.png)

**Comment by nroutasuo** [comment]
Thank you for reporting!

**Comment by nroutasuo** [comment]
Fixed for the upcoming update.
