### ISSUE TITLE
[JS Error] ReferenceError: item is not defined

### ISSUE THREAD

**Issue by Unihedro** [nroutasuo/level13#76]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]
I closed the inn menu without selecting a follower. There were two to be selected. My party was full.

Stacktrace:
```
ReferenceError: item is not defined
    at constructor.refreshCurrent (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:61:107)
    at constructor.initializePopup (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:43:18)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:36:22)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)
```

Below the trace, this was logged:

```
 WARN: No function mapped for action use_in_inn_cancel in PlayerActionFunctions.performAction PlayerActionFunctions.js:257
 WARN: No callout could be created for action button with action undefined. No content for callout. UIFunctions.js:419
```

**Comment by nroutasuo** [comment]
Thanks for the details!
