### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'toggleClass' of undefined

### ISSUE THREAD

**Issue by Pudding01** [nroutasuo/level13#85]
Details:
I clicked the send caravan button from one of my camps while another camp was sending a caravan to the same recipient. I've done that before without issue so I don't know why this happened now. (the recipient wants ropes and will give metal)

Stacktrace:
TypeError: Cannot read property 'toggleClass' of undefined
    at constructor.updateButtonCalloutCosts (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:237:27)
    at constructor.updateButtonCallout (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:205:26)
    at constructor.updateButtons (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:157:9)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:134:18)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment]
Thank you for reporting!

**Comment by nroutasuo** [comment]
Fixed for the upcoming update.
