### ISSUE TITLE
[JS Error] ReferenceError: item is not defined

### ISSUE THREAD

**Issue by sd1530393** [nroutasuo/level13#91]
Details:
[Fill in any details here that you think will help tracking down this bug, such as what you did in the game just before it happened.]

bug in INN, can't hire more followers.

Stacktrace:
ReferenceError: item is not defined
    at constructor.refreshCurrent (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:61:107)
    at constructor.initializePopup (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:43:18)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:36:22)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment]
Thank you for reporting this issue! I'm closing this ticket since the issue has already been reported but I will fix it the next update.
