### ISSUE TITLE
[JS Error] TypeError: Cannot read property 'toggleClass' of undefined

### ISSUE THREAD

**Issue by foop05** [nroutasuo/level13#95]
Details:
try to send caravan to bone crossing from level 13
Stacktrace:
TypeError: Cannot read property 'toggleClass' of undefined
    at constructor.updateButtonCalloutCosts (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:237:27)
    at constructor.updateButtonCallout (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:205:26)
    at constructor.updateButtons (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:157:9)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutElementsSystem.js:134:18)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment]
Thank you for reporting! I'm closing the issue as there is already a fix ready that will be part of the next update.
