### ISSUE TITLE
[JS Error] ReferenceError: item is not defined

### ISSUE THREAD

**Issue by asyncViridian** [nroutasuo/level13#96]
Details:
In Camp on level 12, clicked Recruit and then Cancel. Of note: it said I didn't have enough food and water (15 each) to recruit, but I did.

Stacktrace:
ReferenceError: item is not defined
    at constructor.refreshCurrent (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:61:107)
    at constructor.initializePopup (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:43:18)
    at constructor.update (https://nroutasuo.github.io/level13/src/game/systems/ui/UIOutPopupInnSystem.js:36:22)
    at constructor.update (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:15165)
    at r.execute (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:4611)
    at n.Signal.dispatch (https://nroutasuo.github.io/level13/lib/ash/ash.min.js:14:6738)
    at constructor.tick (https://nroutasuo.github.io/level13/lib/brejep/tickprovider.js:44:29)

**Comment by nroutasuo** [comment]
Thank you for reporting! I'm closing the issue as there is already a fix ready that will be part of the next update.
